spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/main_project?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf-8&serverTimezone=Australia/Melbourne
    username: root
    password: 1231



